name: "Continuous Integration"

env:
  GH_OAUTH_TOKEN: ${{ secrets.GH_OAUTH_TOKEN }}

on:
  push:
    branches:
      - "develop"
      - "staging"
  pull_request:
    branches:
      - "develop"
      - "staging"

jobs:
  integration:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Lint TypeScript code"
        run: "yarn run lint"

      # - name: "Run unit tests"
      # run: "yarn run test:unit"

      - name: "Run integration tests"
        run: "yarn run test:integration"
